version: "3"

services:
  app:
    build: .
    ports:
      - "3333:3333"
    command: yarn dev:server
  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: fatec
      POSTGRES_USER: fatec